theme: null
markdown: kramdown

# kramdown:
#   parse_block_html: true

plugins:
  - jekyll-scholar

# =========================
# JEKYLL SCHOLAR
# =========================

scholar:
  source: assets/files
  bibliography: papers.bib

  bibliography_template: bib

  style: apa
  locale: en

  sort_by: year
  order: descending

  query: "@*"


# =========================
# DEFAULT LAYOUT
# =========================

defaults:
  - scope:
      path: ""
    values:
      layout: default
